In [3]:
a = [2, 1, 9, 7, 5]

5-element Vector{Int64}:
 2
 1
 9
 7
 5

In [4]:
sort(a)

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [5]:
a

5-element Vector{Int64}:
 2
 1
 9
 7
 5

In [6]:
sort!(a)

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [7]:
a

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [8]:
a = [2, 1, 9, 7, 5]

5-element Vector{Int64}:
 2
 1
 9
 7
 5

In [9]:
b = sortperm(a)

5-element Vector{Int64}:
 2
 1
 5
 4
 3

In [10]:
a[b]

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [11]:
c = zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [12]:
sortperm!(c, a)

5-element Vector{Int64}:
 2
 1
 5
 4
 3

In [13]:
a[c]

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [14]:
function buble_sort!(a)
    n = length(a)
    for k in 1:n-1
        istranspose = false
        for i in 1:n-k
            if a[i] > a[i+1]
                a[i], a[i+1] = a[i+1], a[i]
                istranspose = true
            end
        end
        if istranspose == false
            break
        end
    end
    return a
end

buble_sort! (generic function with 1 method)

In [15]:
function insert_sort!(vector)
    n = 1
    #ИНВАРИАНТ: срез vector[1:n] - отсортирован
    while n < length(vector)
        n += 1
        i = n
        while i > 1 && vector[i-1] > vector[i]
            vector[i], vector[i-1] = vector[i-1], vector[i]
            i -= 1
        end
    end
    return vector
end

insert_sort! (generic function with 1 method)

In [16]:
Base. sort!(vector::AbstractVector) = buble_sort!(vector)

In [17]:
Base. sort(vector::AbstractVector) = sort!(deepcopy(vector))

In [18]:
Base. sortperm!(vector1::AbstractVector, vector2::AbstractVector) = begin
    sorted = sort(vector2)
    for i in 1:length(sorted)
        vector1[i] = findfirst(==(vector2[i]), sorted)
    end
    return vector1
end

In [19]:
Base. sortperm(vector::AbstractVector) = sortperm!(zeros(Int, length(vector)), vector)

In [20]:
Base. issorted(vector::AbstractVector) = vector == sort(vector)

In [21]:
a

5-element Vector{Int64}:
 2
 1
 9
 7
 5

In [22]:
a[sortperm(a)]

5-element Vector{Int64}:
 1
 2
 5
 7
 9

In [23]:
issorted(a[sortperm(a)])

true

In [24]:
function comb_sort!(a::AbstractVector, factor=1.2473309)
    step = length(a)
    while step >= 1
        for i in 1:length(a)-step
            if a[i] > a[i+step]
                a[i], a[i+step] = a[i+step], a[i]
            end
        end
        step = Int(floor(step/factor))
    end
    buble_sort!(a)
end

comb_sort! (generic function with 2 methods)

In [25]:
function shell_sort_alt!(a::AbstractVector)
    n = length(a)
    step_series = (n÷2^i for i in 1:Int(floor(log2(n))))
    for step in step_series
        for i in firstindex(a):step-1
            insert_sort!(@view(a[i:step:end]))
        end
    end
    return a
end

shell_sort_alt! (generic function with 1 method)

In [26]:
@inline
function Base.merge!(a1, a2, a3)::Nothing
    i1, i2, i3 = 1, 1, 1
    @inbounds while i1 <= length(a1) && i2 <= length(a2)
        if a1[i1] < a2[i2]
            a3[i3] = a1[i1]
            i1 += 1
        else
            a3[i3] = a2[i2]
            i2 += 1
        end
        i3 += 1
    end
    @inbounds if i1 > length(a1)
        a3[i3:end] .= @view(a2[i2:end])
    else
        a3[i3:end] .= @view(a1[i1:end])
    end
    nothing
end

In [27]:
function merge_sort!(a)
    b = similar(a)
    N = length(a)
    n = 1
    @inbounds while n < N
        K = div(N, 2n)
        for k in 0:K-1
            merge!(@view(a[(1:n).+k*2n]),
            @view(a[(n+1:2n).+k*2n]), @view(b[(1:2n).+k*2n]))
        end
        if N - K*2n > n
            merge!(@view(a[(1:n).+K*2n]),
            @view(a[K*2n+n+1:end]), @view(b[K*2n+1:end]))
        elseif 0 < N - K*2n <= N
            b[K*2n+1:end] .= @view(a[K*2n+1:end])
        end
        a, b = b, a
        n *= 2
    end
    if isodd(log2(n))
        b .= a
        a = b
    end
    return a
end

merge_sort! (generic function with 1 method)

In [28]:
function part_sort!(a, b)
    N = length(a)
    K = 0; L = 0; M = N
    #Инвариант: a[1:K] < b && a[K+1:L] == b && a[M+1:N] > b
    while L < M
        if a[L+1] == b
            L += 1
        elseif a[L+1] > b
            a[L+1], a[M] = a[M], a[L+1]
            M -= 1
        else
            L += 1; K += 1
            a[L], a[K] = a[K], a[L]
        end
    end
    return K, M+1
end

part_sort! (generic function with 1 method)

In [29]:
function quick_sort!(a)
    if isempty(a)
        return a
    end
    N = length(a)
    K, M = part_sort!(a, a[rand(1:N)])
    quick_sort!(@view(a[1:K]))
    quick_sort!(@view(a[M:N]))
    return a
end

quick_sort! (generic function with 1 method)

In [30]:
buble_sort!([i for i in 1:1_000_000_000])

1000000000-element Vector{Int64}:
          1
          2
          3
          4
          5
          6
          7
          8
          9
         10
         11
         12
         13
          ⋮
  999999989
  999999990
  999999991
  999999992
  999999993
  999999994
  999999995
  999999996
  999999997
  999999998
  999999999
 1000000000

In [31]:
insert_sort!([i for i in 1:1_000_000_000])

1000000000-element Vector{Int64}:
          1
          2
          3
          4
          5
          6
          7
          8
          9
         10
         11
         12
         13
          ⋮
  999999989
  999999990
  999999991
  999999992
  999999993
  999999994
  999999995
  999999996
  999999997
  999999998
  999999999
 1000000000

In [32]:
shell_sort_alt!([i for i in 1:1_000_000_000])

1000000000-element Vector{Int64}:
          1
          2
          3
          4
          5
          6
          7
          8
          9
         10
         11
         12
         13
          ⋮
  999999989
  999999990
  999999991
  999999992
  999999993
  999999994
  999999995
  999999996
  999999997
  999999998
  999999999
 1000000000

In [33]:
comb_sort!([i for i in 1:1_000_000_000])

1000000000-element Vector{Int64}:
          1
          2
          3
          4
          5
          6
          7
          8
          9
         10
         11
         12
         13
          ⋮
  999999989
  999999990
  999999991
  999999992
  999999993
  999999994
  999999995
  999999996
  999999997
  999999998
  999999999
 1000000000

In [34]:
merge_sort!([i for i in 1:1_000_000_000])

LoadError: OutOfMemoryError()

In [ ]:
quick_sort!([i for i in 1:1_000_000_000])

In [ ]:
InsertionSort([i for i in 1:1_000_000_000])

In [ ]:
MergeSort([i for i in 1:1_000_000_000])

In [ ]:
QuickSort([i for i in 1:1_000_000_000])

In [ ]:
function hoar_median(arr)
    arr = quick_sort!(arr)
    if length(arr) % 2 == 1
        return arr[Int(ceil(length(arr) / 2))]
    else
        return (arr[Int(length(arr) / 2) + 1] + arr[Int(length(arr) / 2)])/2
    end
end

hoar_median (generic function with 1 method)

In [ ]:
hoar_median([6, 5, 4, 3, 2, 1])

3.5

In [ ]:
function heap!(array)
    N = length(array)
    for i in 1:N÷2
        if array[i] < array[2i]
            array[i], array[2i] = array[2i], array[i]
        end
        if 2i+1 <= N && array[i] < array[2i+1]
            array[i], array[2i+1] = array[2i+1], array[i]
        end
    end
    return array
end

heap! (generic function with 1 method)

In [ ]:
function down_first!(heap::AbstractVector)::Nothing
    index = 1
    N = length(heap)
    while index < N÷2
        if heap[index] < heap[2index]
            heap[index], heap[2index] = heap[2index], heap[index]
        end
        if 2index + 1 <= N && heap[index] < heap[2index+1]
            heap[index], heap[2index+1] = heap[2index+1], heap[index]
        end
        index *= 2
    end
end

down_first! (generic function with 1 method)

In [ ]:
function heap_sort!(heap::AbstractVector)
    heap = heap!(heap)
    N = length(heap)
    #Инвариант: heap[1:N] - max heap && heap[N+1:end] - sorted part of array
    while N > 3
        heap[1], heap[N] = heap[N], heap[1]
        N -= 1
        down_first!(@view(heap[1:N]))
    end
    
    return heap
end

heap_sort! (generic function with 1 method)

In [ ]:
heap_sort!([2, 1, 9, 7, 5, 6, 3])

7-element Vector{Int64}:
 1
 2
 3
 5
 6
 7
 9

In [ ]:
function calc_sort!(a::AbstractVector{<:Integer})
    min_val, max_val = extrema(a)
    num_val = zeros(Int, max_val-min_val+1)
    for val in a
        num_val[val-min_val+1] += 1
    end
    k = 0
    for (i, num) in enumerate(num_val)
        a[k+1:k+num] .= min_val+i-1
        k += num
    end
    return a
end

calc_sort! (generic function with 1 method)

In [ ]:
calc_sort!([2, 1, 9, 7, 5, 6, 3])

7-element Vector{Int64}:
 1
 2
 3
 5
 6
 7
 9

In [ ]:
function binary_search(arr::AbstractVector, number)
    left = 1
    right = length(arr)

    while left <= right
        mid = Int(floor((left + right) / 2))
        if arr[mid] == number
            return mid
        elseif number > arr[mid]
            left = mid + 1
        else
            right = mid - 1
        end
    end
end

binary_search (generic function with 1 method)

In [ ]:
binary_search([1, 2, 3, 4, 5, 6, 7, 8], 3)

3

In [ ]:
function mean_square_deviation(a::AbstractVector)
    mean = sum(a)/length(a)
    var = 0
    for i in a
        var += (i - mean)^2
    end
    return sqrt(var/length(a))
end

mean_square_deviation (generic function with 1 method)

In [ ]:
function sort_matrix_1!(a::AbstractMatrix)
    msd = zeros(AbstractFloat, size(a)[2])
    cols = [Vector(i) for i in eachcol(a)]

    for (i, j) in enumerate(cols)
        msd[i] = mean_square_deviation(j)
    end

    cols = cols[sortperm(msd)]

    return hcat(cols ...)
end

sort_matrix_1! (generic function with 1 method)

In [ ]:
function sort_matrix_2!(a::AbstractMatrix)
    cols = [Vector(i) for i in eachcol(a)]
    cols = sort(cols, by=mean_square_deviation)
    return hcat(cols ...)
end

sort_matrix_2! (generic function with 1 method)

In [ ]:
A = [[9, 12, 15] [1, 3, 5] [6, 7, 8]]

3×3 Matrix{Int64}:
  9  1  6
 12  3  7
 15  5  8

In [ ]:
sort_matrix_1!(A)

3×3 Matrix{Int64}:
 6  1   9
 7  3  12
 8  5  15

In [ ]:
A

3×3 Matrix{Int64}:
  9  1  6
 12  3  7
 15  5  8

In [ ]:
sort_matrix_2!(A)

3×3 Matrix{Int64}:
 6  1   9
 7  3  12
 8  5  15